
frontend:
  image:
    name: tecpi/monstericon
    tag: latest
  service:
    port: 5000
imagebackend:
  image:
    name: amouat/dnmonster
    tag: "1.0"
redis:
  image:
    name: redis
    tag: latest

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: monsterchart.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []