apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- dnmonster.yaml
- redis.yaml
- monstericon.yaml
- monster-ingress.yaml
namespace: dev
images:
- name: registry.gitlab.com/e-lie/cicd_gitlab_argocd_corrections
  newTag: f5008b6283bcbcbfc033804ffbdf4aa70f8c1889
