version: '3'
services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CONTEXT=DEV
    networks:
      - monster_network

  imagebackend:
    image: amouat/dnmonster:1.0
    networks:
      - monster_network

  redis:
    image: redis
    networks:
      - monster_network

networks:
  monster_network:
    driver: bridge
