
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: registry.kluster.ptych.net/frontend
deploy:
  helm:
    releases:
      - name: monsterchart
        chartPath: ./monsterchart
        artifactOverrides:
          imageKey: registry.kluster.ptych.net/frontend
        imageStrategy:
          fqn: {}