apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- dnmonster.yaml
- redis.yaml
- monstericon.yaml
- monster-ingress.yaml
namespace: prod
images:
- name: registry.gitlab.com/e-lie/cicd_gitlab_argocd_corrections
  newTag: c04bb1ab083d7bd3e5a8f8050a251068ebf434f9
