apiVersion: v1
kind: Service
metadata:
  name: redis-{{ include "monsterchart.fullname" . }}
  labels:
    app: monsterstack
spec:
  ports:
    - port: 6379
  selector:
    app: monsterstack
    partie: redis-{{ include "monsterchart.fullname" . }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ include "monsterchart.fullname" . }} 
  labels:
    app: monsterstack
spec:
  selector:
    matchLabels:
      app: monsterstack
      partie: redis-{{ include "monsterchart.fullname" . }}
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: monsterstack
        partie: redis-{{ include "monsterchart.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.redis.image.name }}:{{ .Values.redis.image.tag }}
        name: redis
        ports:
        - containerPort: 6379
          name: redis