apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- monstericon-ingress.yaml

patchesStrategicMerge:
- dnmonster-deploy.yaml
- monstericon-deploy.yaml
- monstericon-svc.yaml

# namePrefix: "beta-"
# nameSuffix: "-001"