apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-chart
  namespace: argocd 
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 5.7.2
    helm:
      values: |
        wordpressUsername: elie
        wordpressPassword: myunsecurepassword
        wordpressBlogName: Kubernetes example blog

        replicaCount: 3

        service:
          type: ClusterIP

        ingress:
          enabled: true
          hostname: wordpress.elie.formation.dopl.uk
          pathType: Prefix
          tls: true
          certManager: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx