apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- dnmonster-deploy.yaml
- dnmonster-svc.yaml
- redis-deploy.yaml
- redis-svc.yaml
- monstericon-deploy.yaml
- monstericon-svc.yaml
- monstericon-ingress.yaml