apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- monstericon-ingress.yaml

patchesStrategicMerge:
- dnmonster-deploy.yaml
- monstericon-deploy.yaml
- monstericon-svc.yaml

images:
- name: monstericon
  newName: ${IMAGE}
  newTag: ${TAG_BETA}

vars:
- name: INGRESS_SUBDOMAIN
  objref:
    kind: ConfigMap
    name: environment-variables
    apiVersion: v1
  fieldref:
    fieldpath: data.INGRESS_SUBDOMAIN

configMapGenerator:
- name: environment-variables
  envs: [release.env]
  behavior: create
